name: RISC V Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install software
        run: |
          sudo apt-get update
          sudo apt-get install riscv64-elf-gcc riscv64-elf-newlib

      - name: Build
        run: |
          make check CC=riscv64-elf-gcc
